<?php

/**
 * Created by PhpStorm.
 * User: hust
 * Date: 12.07.2017
 * Time: 22:03
 */
class Transactions extends Storable
{
    public $id;
    public $user_id;
    public $date;
    public $summ;
    public $profit;
    public $start_time;
    public $end_time;


    static function getAll($class)
    {
        return parent::getAll($class); // TODO: Change the autogenerated stub
    }

    static function getById($class, $id)
    {
        return parent::getById($class, $id); // TODO: Change the autogenerated stub
    }

    static function tableName()
    {
        return 'transactions';
    }


    static function getTransactions($limit, $page)
    {
        $db = Database::getDB();
        $limit = empty($limit) ? '' :  ' LIMIT '.$limit;
        $offset = empty($page) ? '' :  ' OFFSET '.(($page - 1) * $limit);
        $query = 'SELECT * FROM '.static::tableName().$limit.$offset.';';
        $rows = $db->getQuery($query);
        return $rows;//static::getObjects(__CLASS__, $rows);
    }

    static function getTransactionsForDate($start_time, $end_time)
    {
        $db = Database::getDB();
        $start = '"'.$start_time.'"';
        $end = '"'.$end_time.'"';
        $query = 'SELECT * FROM '.static::tableName().' WHERE date BETWEEN '.$start.' AND '.$end.';';
        $data = $db->getQuery($query);
        return $data;
    }

    public function getUser()
    {
        return User::getById($this->user_id);
    }


}